- name: Simple play
  hosts: localhost
  roles:
    - etc_files

# tasks:
#   - name: Hello
#     ansible.builtin.debug:
#       msg: "Hello {{ ansible_facts['distribution'] }} {{ ansible_facts }} "
#   - name: Pavza
#     pause:
#       prompt: yes # not required. Optional text to use for the prompt message.
#       echo: yes # not required. Controls whether or not keyboard input is shown when typing. Has no effect if 'seconds' or 'minutes' is set.
