- name: Update pacman cache
  become: true
  pacman:
    update_cache: yes
  tags:
    - install
    - extra

- name: Installing extra packages
  become: true
  pacman:
    name:
      - emacs-wayland
      - lazygit
      - git-delta
      - tealdeer
      - matugen
  

  tags:
    - install
    - extra

- name: Tldr
  shell: tldr --update
  tags: 
    - extra
