---
- name: Update pacman cache
  become: true
  pacman:
    update_cache: true
  tags:
    - install
    - extra

- name: Installing extra packages
  become: true
  pacman:
    name:
      - emacs-wayland
      - lazygit
      - git-delta
      - tealdeer
      - matugen
      - zen-browser-bin
      - fastfetch
      - urbanlifestyle-sddm-theme

  tags:
    - install
    - extra

- name: Set SDDM theme to urbanlifestyle
  ansible.builtin.ini_file:
    path: /etc/sddm.conf.d/theme.conf
    section: Theme
    option: Current
    value: urbanlifestyle
    create: true
  become: true
  tags:
    - extra

- name: Tldr
  ansible.builtin.command: tldr --update
  tags:
    - extra
