---
- name: Enabling tlp service
  become: true
  ansible.builtin.command: systemctl enable tlp
  tags: service

# - name: Enabling auto-cpufreq service
#   become: true
#   shell: systemctl enable auto-cpufreq
#   tags: service
